language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "nightly" # currently points to 3.6-dev
# command to install dependencies

install:
  - pip install -r requirements.txt
  - pip install unittest-xml-reporting
# command to run tests
script:
  - cd ..
  - mkdir test-reports
  - cd test-reports
  - python -m xmlrunner discover -s ../twistes/twistes/tests/ -t ../twistes/
